openapi: 3.0.3

info:
  description: This is the API model for TCN Server, https://github.com/TCNCoalition/TCN/blob/main/README.md, protocol 0.4.0
  version: 0.4.0
  title: TCN Server
  license:
    name: MIT License
    url: https://github.com/Co-Epi/data-models/blob/master/LICENSE

paths:
  /tcnreport/0.4.0:
    post:
      summary: Submit symptom or infection report
      description: Users submit symptom / infection reports and reveal the secret TCN Key in their application
        as bytes in format 'rvk || tck_{j1-1} || le_u16(j1) || le_u16(j2) || memo'. Details of the TCN protocol
        can be found here, https://github.com/TCNCoalition/TCN/blob/main/README.md

      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              format: byte

      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: ${lambda_invoke_arn}
        httpMethod: POST

      responses:
        '200':
          description: The report was submitted successfully
        '400':
          description: The report is not encoded in the correct format
        '401':
          description: The report signature validation has failed
        '500':
          description: Internal Server Error

    get:
      summary: Returns a list of reports generated for a given interval number.

      description: Interval number is a positive integer that corresponds to a specific fixed time interval and can
        be calculated as (unix_epoch_time_seconds / time_interval_seconds).
        Current value of time_interval_ms is (6 * 3600) or 6 hours. When not provided, returns the reports
        corresponding to the latest interval batch.

      parameters:
        - in: query
          name: intervalNumber
          description: Positive integer that corresponds to a specific fixed time interval and can
            be calculated as (unix_epoch_time_seconds / time_interval_seconds). When not provided, current
            interval number is assumed.
          required: false
          schema:
            type: integer
            format: int64
          example: 158874736
        - in: query
          name: intervalLength
          description: The interval length in seconds used by the client to calculate intervalNumber.
            The server will respond with a 401 if the interval length does not match the expected length.
          required: false
          schema:
            type: integer
            format: int64
          example: 21600

      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: ${lambda_invoke_arn}
        httpMethod: POST

      responses:
        '200':
          description: List of infection/symptom reports generated during the specified intervalNumber
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: byte
        '400':
          description: Request Parameter Invalid
        '432':
          description: intervalLength is not valid for the specified intervalNumber
        '500':
          description: Internal Server Error
